### ISSUE TITLE
Add a ReadMe to the project with instructions on how to clone to IntelliJ, make and push a commit and open a PR

### ISSUE THREAD

**Issue by PPartisan** [PPartisan/RockPaperScissorsTests#10]

**Comment by PPartisan** [comment]
I have some thoughts, but it's better to review them during Saturday's meetings. In the meantime, let's see if anyone else leaves any comments.

**Comment by second-ed** [comment]
I wouldn't mind there being something on our project specific git branching name conventions and conventional commit messages too

**Comment by PPartisan** [comment]
I'm moving this ticket to done as it's a trial-run for our actual project. We've agreed to keep the ReadMe short and move specifics related to git, IDE interactions, branching strategies etc. into the wiki and link to them from the ReadMe.
