### ISSUE TITLE
Incorporate Detekt static analysis into the project

### ISSUE THREAD

**Issue by PPartisan** [PPartisan/RockPaperScissorsTests#12]
Additionally, how do we configure it?

**Comment by second-ed** [comment]
looks like you have config down on #17 add me to review if you want

**Comment by second-ed** [comment]
@PPartisan @Robert-Davie review this ticket when you can please and then feel free to move to done if you're happy with detekt in it's current config as of #17

**Comment by PPartisan** [comment]
Yep I'm happy with this in its current state. It could be worth adding a link to the Detekt Wiki for their configuration file to our own wiki at some point, but I'm fine with this for now.
