### ISSUE TITLE
Update the Wiki with a "learning resources" section

### ISSUE THREAD

**Issue by PPartisan** [PPartisan/RockPaperScissorsTests#9]

**Comment by Robert-Davie** [comment]
updated the wiki with some learning resources

**Comment by PPartisan** [comment]
I'm happy to move this over to done. Any objections @second-ed @DuniaAli ?

**Comment by second-ed** [comment]
@Robert-Davie please add https://learngitbranching.js.org/ to the git resources, then happy to call it done

**Comment by PPartisan** [comment]
I've moved this across to done - if you have further recommendations Ed then let me know in the next meeting and we can create new tickets.
